// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFzZHj0F7euWav6uet5l-BK_3YZovzhc',
    appId: '1:975932830965:web:04732e921f66c5e7bbc1bc',
    messagingSenderId: '975932830965',
    projectId: 'carrental-343fb',
    authDomain: 'carrental-343fb.firebaseapp.com',
    databaseURL: 'https://carrental-343fb-default-rtdb.firebaseio.com',
    storageBucket: 'carrental-343fb.firebasestorage.app',
    measurementId: 'G-C48YZY7J1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRKyuYllwIWrTmJdLcaqWaT3o_zhOrH1Y',
    appId: '1:975932830965:android:11f9db9a42f61a85bbc1bc',
    messagingSenderId: '975932830965',
    projectId: 'carrental-343fb',
    databaseURL: 'https://carrental-343fb-default-rtdb.firebaseio.com',
    storageBucket: 'carrental-343fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9lCskJiznpW5pSc3bGDH4fS14XxfD4g4',
    appId: '1:975932830965:ios:846e63bb6b58f97fbbc1bc',
    messagingSenderId: '975932830965',
    projectId: 'carrental-343fb',
    databaseURL: 'https://carrental-343fb-default-rtdb.firebaseio.com',
    storageBucket: 'carrental-343fb.firebasestorage.app',
    iosBundleId: 'com.example.carApp',
  );
}
